#!/bin/bash

# login based on https://www.mediawiki.org/wiki/API:Client_code/Bash

read user password < auth
if [ -z "$user" -o -z "$password" ]; then
    echo "$0: error: no authentication data found in \`auth\` file" >&2
    exit 1
fi
api='http://www.wikidata.org/w/api.php'
cookie_jar="wikicj"
user_agent="$user Patroller Bot Development"

get() {
    curl -s -S \
         --location \
         --cookie $cookie_jar \
         --cookie-jar $cookie_jar \
         --user-agent "$user_agent" \
         --keepalive-time 60 \
         --header "Accept-Language: en-us" \
         --header "Connection: keep-alive" \
         --compressed \
         --data-urlencode "format=json" \
         "$@" \
         "$api"
}

#Login part 1
CR=$(get \
         --data-urlencode "action=login" \
         --data-urlencode "lgname=${user}" \
         --data-urlencode "lgpassword=${password}" \
         --request "POST")

TOKEN=$(echo "$CR" | jq --raw-output .login.token)
if [ -z "$TOKEN" ]; then
    echo "Login part 1 failed."
    echo $CR
    exit 1
fi

#Login part 2
CR=$(get \
         --data-urlencode "action=login" \
         --data-urlencode "lgname=${user}" \
         --data-urlencode "lgpassword=${password}" \
         --data-urlencode "lgtoken=${TOKEN}" \
         --request "POST")

changes() {
    get \
        --data-urlencode "action=query" \
        --data-urlencode "list=recentchanges" \
        --data-urlencode "rcshow=!patrolled" \
        --data-urlencode "rcnamespace=0" \
        --data-urlencode "rcprop=ids|comment" \
        --data-urlencode "rclimit=50"
}

# input: literal start of comments
# output: those revisions matching that start, in the format:
# revid comment
# 212664081 /* clientsitelink-update:0|Xwiki|Xwiki:FOO|Xwiki:BAR */
filterchanges() {
    changes | jq --raw-output '
        .query.recentchanges |
        map(select(.comment | startswith("'"$1"'"))) |
        map((.revid | tostring) + " " + .comment) |
        .[]'
}

pagemoves() {
    filterchanges "/* clientsitelink-update:0|"
}
pageremoves() {
    filterchanges "/* clientsitelink-remove:1|| */ "
}

pagemoves

pageremoves
